#!/usr/bin/env python3
"""
discovery_report.py — SI8 Product Discovery Report Generator

Scans ALL Supabase responses (not just warm) for product discovery signals using
`is_product_feedback()`. This includes pass and naf replies — a polite "not for us"
that describes current workflow or quantifies a pain is more valuable than a vague
warm reply.

Output: 03_Sales/DISCOVERY-PERFORMANCE-LOG.md (latest)
        03_Sales/discovery-reports/DISCOVERY-REPORT-YYYY-MM-DD.md (dated archive)

Usage:
  python tools/campaign-report/discovery_report.py
  python tools/campaign-report/discovery_report.py --supabase data/supabase-exports/supabase-export-YYYY-MM-DD.csv
  python tools/campaign-report/discovery_report.py --dry-run

See 03_Sales/CAMPAIGN-REPORT-METHODOLOGY.md for context on the full report workflow.
"""

import csv, sys, os, re, glob, argparse
from collections import defaultdict
from datetime import date

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'linkedin-analysis'))
from classify import extract_reply, classify_reply, is_product_feedback

REPO_ROOT   = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
OUTPUT_PATH = os.path.join(REPO_ROOT, '03_Sales', 'DISCOVERY-PERFORMANCE-LOG.md')
ARCHIVE_DIR = os.path.join(REPO_ROOT, '03_Sales', 'discovery-reports')

# Geo normalization — kept in sync with report.py
DRIP_TO_NORM = {
    'Dubai': 'UAE/Dubai', 'UAE': 'UAE/Dubai',
    'England': 'London/UK', 'London': 'London/UK', 'UK': 'London/UK',
    'Amsterdam': 'Netherlands', 'Netherlands': 'Netherlands',
    'Singapore': 'Singapore',
    'Los Angeles': 'USA', 'LA': 'USA', 'USA': 'USA',
    'Berlin': 'Germany', 'Germany': 'Germany', 'DACH': 'Germany',
    'Sydney': 'Sydney/AU', 'Australia': 'Sydney/AU',
    'Paris': 'France/Paris', 'France': 'France/Paris',
    'Stockholm': 'Sweden/Stockholm', 'Sweden': 'Sweden/Stockholm', 'STHM': 'Sweden/Stockholm',
    'Global': 'Other',
}


def norm_location(location: str) -> str:
    loc = location.lower()
    if any(x in loc for x in ['dubai', 'uae', 'united arab emirates', 'abu dhabi']): return 'UAE/Dubai'
    if any(x in loc for x in ['london', 'england', 'united kingdom']): return 'London/UK'
    if 'singapore' in loc: return 'Singapore'
    if any(x in loc for x in ['amsterdam', 'netherlands']): return 'Netherlands'
    if any(x in loc for x in ['berlin', 'germany', 'munich', 'hamburg']): return 'Germany'
    if any(x in loc for x in ['paris', 'france']): return 'France/Paris'
    if any(x in loc for x in ['stockholm', 'sweden', 'gothenburg']): return 'Sweden/Stockholm'
    if any(x in loc for x in ['sydney', 'australia', 'melbourne']): return 'Sydney/AU'
    if any(x in loc for x in ['los angeles', 'new york', 'united states', 'usa', 'chicago']): return 'USA'
    return 'Other'


def pct(n, d): return f"{n / d * 100:.1f}%" if d else "—"


def find_latest_supabase() -> str:
    pattern = os.path.join(REPO_ROOT, 'data', 'supabase-exports', 'supabase-export-*.csv')
    files = sorted(glob.glob(pattern), reverse=True)
    if not files:
        raise FileNotFoundError(f"No Supabase CSV found at {pattern}")
    return files[0]


def load_supabase(path: str) -> list:
    rows = []
    with open(path, encoding='utf-8') as f:
        for r in csv.DictReader(f):
            if r.get('is_latest_version', '').lower() != 'true':
                continue
            reply = extract_reply(r.get('conversation_raw', ''))
            r['_reply']     = reply
            r['_class']     = classify_reply(reply)
            r['_geo']       = norm_location(r.get('lead_location', ''))
            # Discovery classification runs on the extracted reply only —
            # not conversation_raw, to avoid false positives from JD's own messages
            # (e.g. "legal team" appears in the Legal Friction msg#1 outreach text).
            r['_discovery'] = is_product_feedback(reply)
            rows.append(r)
    return rows


def generate(supabase_rows: list, supabase_path: str) -> str:
    today   = date.today().isoformat()
    L       = []
    a       = L.append
    total   = len(supabase_rows)
    disc    = [r for r in supabase_rows if r['_discovery']]
    n_disc  = len(disc)

    # ── Header ────────────────────────────────────────────────────────────────
    a("# Product Discovery Report — Dripify LinkedIn Outreach")
    a("")
    a(f"**Last updated:** {today}")
    a(f"**Source:** `{os.path.basename(supabase_path)}` (Supabase, `is_latest_version=true`)")
    a(f"**Generated by:** `tools/campaign-report/discovery_report.py`")
    a("")
    a("**What this is:** Replies containing product discovery signals — workflow descriptions,")
    a("pain confirmations, market observations, and product questions — regardless of sales")
    a("classification. Includes pass/naf replies where the lead described their process or")
    a("confirmed the problem space even without buying intent.")
    a("")
    a("**These are NOT sales leads.** Route selected leads to `03_Sales/DISCOVERY-PIPELINE.md`.")
    a("")
    a("---")
    a("")

    # ── Grand Total ───────────────────────────────────────────────────────────
    class_counts = defaultdict(lambda: {'total': 0, 'disc': 0})
    for r in supabase_rows:
        class_counts[r['_class']]['total'] += 1
        if r['_discovery']:
            class_counts[r['_class']]['disc'] += 1

    a("## Grand Total")
    a("")
    a("| Metric | Value |")
    a("|--------|-------|")
    a(f"| Total responses scanned | **{total:,}** |")
    a(f"| Discovery signals found | **{n_disc:,}** ({pct(n_disc, total)}) |")
    a("")
    a("| Sales Class | Responses | Discovery Signals | Signal Rate | Notes |")
    a("|-------------|-----------|-------------------|-------------|-------|")
    class_notes = {
        'warm':    'buying intent + product insight',
        'pass':    'polite no — may describe workflow/pain',
        'naf':     'not a fit — may explain why (competitive intel)',
        'minimal': 'short reply — low signal value',
    }
    for cls in ['warm', 'pass', 'naf', 'minimal']:
        g = class_counts[cls]
        a(f"| {cls} | {g['total']} | {g['disc']} | {pct(g['disc'], g['total'])} | {class_notes[cls]} |")
    a("")
    a("---")
    a("")

    # ── By Geo ────────────────────────────────────────────────────────────────
    geo_totals = defaultdict(lambda: {'total': 0, 'disc': 0})
    for r in supabase_rows:
        g = geo_totals[r['_geo']]
        g['total'] += 1
        if r['_discovery']:
            g['disc'] += 1
    geo_sorted = sorted(
        geo_totals.items(),
        key=lambda x: x[1]['disc'] / max(x[1]['total'], 1),
        reverse=True
    )

    a("## By Geo")
    a("")
    a("| Geo | Responses | Discovery Signals | Signal Rate |")
    a("|-----|-----------|-------------------|-------------|")
    for geo, g in geo_sorted:
        a(f"| {geo} | {g['total']} | {g['disc']} | {pct(g['disc'], g['total'])} |")
    a("")
    a("---")
    a("")

    # ── By Sequence ───────────────────────────────────────────────────────────
    seq_totals = defaultdict(lambda: {'total': 0, 'disc': 0})
    for r in supabase_rows:
        seq = (r.get('campaign_name') or 'Unknown').strip() or 'Unknown'
        g   = seq_totals[seq]
        g['total'] += 1
        if r['_discovery']:
            g['disc'] += 1
    seq_sorted = sorted(
        seq_totals.items(),
        key=lambda x: x[1]['disc'] / max(x[1]['total'], 1),
        reverse=True
    )

    a("## By Sequence")
    a("")
    a("| Sequence | Responses | Discovery Signals | Signal Rate |")
    a("|----------|-----------|-------------------|-------------|")
    for seq, g in seq_sorted:
        a(f"| {seq} | {g['total']} | {g['disc']} | {pct(g['disc'], g['total'])} |")
    a("")
    a("---")
    a("")

    # ── Discovery Signal Checklist ────────────────────────────────────────────
    disc_by_geo = defaultdict(list)
    for r in disc:
        disc_by_geo[r['_geo']].append(r)
    geo_order = sorted(disc_by_geo.keys(), key=lambda g: len(disc_by_geo[g]), reverse=True)

    a("## Discovery Signal Checklist")
    a("")
    a("*Review each lead. If their reply describes workflow, quantifies pain, or reveals a")
    a("product insight worth exploring — add them to `03_Sales/DISCOVERY-PIPELINE.md` → Stage: Signal.*")
    a("")
    a("**Good candidates for discovery follow-up:**")
    a("- Described their current process in detail (even if they're not buying)")
    a("- Quantified the pain (time, cost, frequency, deal impact)")
    a("- Asked a product question that reveals an unmet need or edge case")
    a("- Confirmed the problem exists at their company, even if 'not now'")
    a("- Mentioned a competitor, workaround, or alternative they're using")
    a("")
    a("**Sales class shown in brackets** — [PASS] and [NAF] included intentionally.")
    a("")

    for geo in geo_order:
        leads = disc_by_geo[geo]
        a(f"**{geo}** ({len(leads)} signals):")
        a("")
        for r in leads:
            cls_label = f"[{r['_class'].upper()}]"
            full = r.get('conversation_raw', r['_reply']).strip()
            a(f"- {cls_label}  {r.get('lead_name', '?')} · {r.get('lead_title', '?')} · {r.get('lead_company', '?')}")
            a("")
            for line in full.splitlines():
                a(f"  {line}")
            a("")
        a("")

    return '\n'.join(L)


def main():
    parser = argparse.ArgumentParser(description='SI8 Product Discovery Report Generator')
    parser.add_argument('--supabase', default=None, help='Path to Supabase CSV (default: latest)')
    parser.add_argument('--dry-run',  action='store_true', help='Print to stdout only')
    args = parser.parse_args()

    supabase_path = args.supabase or find_latest_supabase()
    if not os.path.isabs(supabase_path):
        supabase_path = os.path.join(REPO_ROOT, supabase_path)

    print(f"Loading Supabase: {supabase_path}")
    rows   = load_supabase(supabase_path)
    n_disc = sum(1 for r in rows if r['_discovery'])
    print(f"Responses:  {len(rows)} (is_latest_version=true)")
    print(f"Discovery:  {n_disc} signals ({pct(n_disc, len(rows))} signal rate)")

    report = generate(rows, supabase_path)

    if args.dry_run:
        print('\n' + report)
        return

    m           = re.search(r'supabase-export-(\d{4}-\d{2}-\d{2})', supabase_path)
    report_date = m.group(1) if m else date.today().isoformat()
    os.makedirs(ARCHIVE_DIR, exist_ok=True)
    dated_path  = os.path.join(ARCHIVE_DIR, f'DISCOVERY-REPORT-{report_date}.md')

    with open(dated_path, 'w', encoding='utf-8') as f:
        f.write(report)
    with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write(report)

    print(f"\nWritten:  {dated_path}")
    print(f"Latest:   {OUTPUT_PATH}")
    print("Next: review the Discovery Signal Checklist,")
    print("      add selected leads to 03_Sales/DISCOVERY-PIPELINE.md → Stage: Signal")


if __name__ == '__main__':
    main()
