/**
 * Assessment Service
 *
 * Orchestrates the assessment processing lifecycle:
 *   DRAFT → REPORT_GENERATED → SIGNING → SIGNED → DELIVERED
 *
 * This module is the only place that calls the ProvenanceProvider.
 * It is provider-agnostic: pass any ProvenanceProvider implementation.
 *
 * Responsibilities:
 *   - Create and persist Assessment records
 *   - Compute PDF SHA-256
 *   - Download signed asset from provider and store in Supabase Storage
 *   - Advance processing_status through transitions
 *   - Preserve failure diagnostics on error
 *
 * NOT responsible for:
 *   - PDF generation (existing Typst pipeline)
 *   - Reviewer workbook logic
 *   - Customer-facing delivery emails
 */

import crypto from 'crypto'
import { supabaseAdmin } from '@/lib/supabase/admin'
import {
  createAssessment,
  findAssessmentById,
  findAssessmentBySubmissionId,
  generateAssessmentNumber,
  markFailed,
  transitionProcessingStatus,
} from './repository'
import type {
  Assessment,
  AssessmentInsert,
  AssessmentMetadata,
  AssessmentOutcome,
  DigitalSourceTypeUri,
  ProvenanceProvider,
} from '@/types/assessment'
import { DIGITAL_SOURCE_TYPE_URIS } from '@/types/assessment'

// ── Constants ─────────────────────────────────────────────────────────────────

const REVIEWER_ORGANIZATION = 'PMF Strategy Inc. d/b/a SuperImmersive 8'
const METHODOLOGY_VERSION = 'SI8 Reviewer Manual v0.1'
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://app.superimmersive8.com'

// For v1, default to compositeWithTrainedAlgorithmicMedia (covers the typical
// agency composited video workflow).
// TODO v2: make reviewer-settable in the workbook UI.
const DEFAULT_DIGITAL_SOURCE_TYPE: DigitalSourceTypeUri =
  DIGITAL_SOURCE_TYPE_URIS.compositeWithTrainedAlgorithmicMedia

// ── Create assessment ─────────────────────────────────────────────────────────

/**
 * Create an Assessment record from a signed-off workbook.
 * Called by the admin sign route once section_6 is signed off.
 *
 * If an assessment already exists for this submission_id, returns the existing one.
 * This makes the operation idempotent.
 */
export async function createAssessmentFromWorkbook(
  submissionId: string,
  outcome: AssessmentOutcome,
): Promise<Assessment> {
  // Idempotency: return existing assessment if already created
  const existing = await findAssessmentBySubmissionId(submissionId)
  if (existing) return existing

  const assessmentNumber = await generateAssessmentNumber()
  const verificationUrl = `${SITE_URL}/assessment/${assessmentNumber}`

  const insert: AssessmentInsert = {
    submission_id:        submissionId,
    assessment_number:    assessmentNumber,
    assessment_date:      new Date().toISOString().split('T')[0],
    methodology_version:  METHODOLOGY_VERSION,
    reviewer_organization: REVIEWER_ORGANIZATION,
    outcome,
    institutional_status: 'ACTIVE',
    status_reason:        null,
    processing_status:    'DRAFT',
    failure_diagnostic:   null,
    verification_url:     verificationUrl,
    numbers_asset_id:     null,
    signed_asset_path:    null,
    pdf_hash_sha256:      null,
  }

  return createAssessment(insert)
}

// ── Sign flow ─────────────────────────────────────────────────────────────────

export interface SignAssessmentInput {
  assessmentId: string
  /** The compiled PDF buffer (already generated by Typst pipeline) */
  pdfBuffer: Buffer
  /** The raw source MP4 buffer */
  videoBuffer: Buffer
  /** File extension for the source video, e.g. 'mp4' */
  videoExt: string
}

export interface SignAssessmentResult {
  reportHash: string
  numbersAssetId: string
  numbersVerifyUrl: string | null
  signedAssetPath: string
}

/**
 * Run the full signing flow for an assessment.
 *
 * Steps:
 *   1. Compute PDF SHA-256, advance status to REPORT_GENERATED
 *   2. Advance status to SIGNING
 *   3. Call ProvenanceProvider.sign (Numbers Protocol)
 *   4. Download signed asset from provider URL
 *   5. Store signed asset in Supabase Storage (signed-assets bucket)
 *   6. Advance status to SIGNED, persist numbers_asset_id + signed_asset_path
 *
 * On any failure after DRAFT: mark FAILED with diagnostic, never throw silently.
 * Retries are safe: if numbers_asset_id + signed_asset_path are both set, the
 * function returns immediately before any state transitions are attempted.
 */
export async function signAssessment(
  input: SignAssessmentInput,
  provider: ProvenanceProvider,
): Promise<SignAssessmentResult> {
  const { assessmentId, pdfBuffer, videoBuffer, videoExt } = input

  // Fetch the current assessment record via repository (avoids raw supabaseAdmin call)
  const assessment = await findAssessmentById(assessmentId)
  if (!assessment) {
    throw new Error(`Assessment ${assessmentId} not found`)
  }

  // ── Retry guard ───────────────────────────────────────────────────────────
  // Must run before any state transitions. If both numbers_asset_id and
  // signed_asset_path are already set, the Numbers call and Supabase upload
  // completed on a previous attempt. Re-running transitionProcessingStatus
  // would throw because processing_status is no longer DRAFT.
  if (assessment.numbers_asset_id && assessment.signed_asset_path) {
    const reportHash = crypto.createHash('sha256').update(pdfBuffer).digest('hex')
    return {
      reportHash,
      numbersAssetId:   assessment.numbers_asset_id,
      numbersVerifyUrl: null,
      signedAssetPath:  assessment.signed_asset_path,
    }
  }

  // ── Step 1: PDF hash + REPORT_GENERATED ──────────────────────────────────
  const reportHash = crypto.createHash('sha256').update(pdfBuffer).digest('hex')

  await transitionProcessingStatus(assessmentId, 'REPORT_GENERATED', {
    pdfHashSha256: reportHash,
  })

  // ── Step 2: Advance to SIGNING ────────────────────────────────────────────
  await transitionProcessingStatus(assessmentId, 'SIGNING')

  // ── Step 3: Call ProvenanceProvider ──────────────────────────────────────
  const assessmentMeta: AssessmentMetadata = {
    assessmentNumber:     assessment.assessment_number,
    assessmentDate:       assessment.assessment_date,
    reviewerOrganization: assessment.reviewer_organization,
    methodologyVersion:   assessment.methodology_version,
    outcomeCode:          assessment.outcome as AssessmentOutcome,
    verificationUrl:      assessment.verification_url,
  }

  let signedResult
  try {
    signedResult = await provider.sign(videoBuffer, assessmentMeta, {
      digitalSourceType: DEFAULT_DIGITAL_SOURCE_TYPE,
    })
  } catch (err: any) {
    await markFailed(assessmentId, {
      step:      'ProvenanceProvider.sign',
      error:     err?.message ?? String(err),
      timestamp: new Date().toISOString(),
    })
    throw err
  }

  // ── Step 4: Download signed asset from provider URL ───────────────────────
  let signedVideoBuffer: Buffer
  try {
    const downloadRes = await fetch(signedResult.signedAssetUrl)
    if (!downloadRes.ok) {
      throw new Error(`Download failed: HTTP ${downloadRes.status} from ${signedResult.signedAssetUrl}`)
    }
    signedVideoBuffer = Buffer.from(await downloadRes.arrayBuffer())
  } catch (err: any) {
    await markFailed(assessmentId, {
      step:      'DownloadSignedAsset',
      error:     err?.message ?? String(err),
      timestamp: new Date().toISOString(),
    })
    throw err
  }

  // ── Step 5: Store signed asset in Supabase Storage ───────────────────────
  const storagePath = `${assessment.assessment_number}/signed.${videoExt}`
  try {
    const { error: uploadErr } = await supabaseAdmin.storage
      .from('signed-assets')
      .upload(storagePath, signedVideoBuffer, {
        contentType: 'video/mp4',
        upsert: true,
      })

    if (uploadErr) {
      throw new Error(`Supabase upload error: ${uploadErr.message}`)
    }
  } catch (err: any) {
    await markFailed(assessmentId, {
      step:      'StoreSignedAsset',
      error:     err?.message ?? String(err),
      timestamp: new Date().toISOString(),
    })
    throw err
  }

  // ── Step 6: Advance to SIGNED ─────────────────────────────────────────────
  await transitionProcessingStatus(assessmentId, 'SIGNED', {
    numbersAssetId:   signedResult.provenanceAssetId,
    signedAssetPath:  storagePath,
  })

  return {
    reportHash,
    numbersAssetId:   signedResult.provenanceAssetId,
    numbersVerifyUrl: signedResult.verificationUrl ?? null,
    signedAssetPath:  storagePath,
  }
}

// ── Build C2PA assertion payload ──────────────────────────────────────────────

/**
 * Build the Zone A C2PA custom assertion payload for the Numbers Capture API.
 *
 * Approved embedded fields (si8.commercial-assurance/v1 namespace):
 *   - si8:assessment_number
 *   - si8:assessment_date
 *   - si8:reviewer_organization
 *   - si8:methodology_version
 *   - si8:outcome_code
 *   - si8:verification_url
 *
 * NOT embedded: confidence, report_hash (v1), findings, customer info,
 *   tool names, evidence, likeness assessment, commercial_authorization.
 *
 * The digitalSourceType IPTC URI is provided separately as a standard C2PA field.
 */
export function buildC2PAManifest(
  assessment: Pick<
    Assessment,
    | 'assessment_number'
    | 'assessment_date'
    | 'reviewer_organization'
    | 'methodology_version'
    | 'outcome'
    | 'verification_url'
  >,
): Record<string, string> {
  return {
    'si8:assessment_number':    assessment.assessment_number,
    'si8:assessment_date':      assessment.assessment_date,
    'si8:reviewer_organization': assessment.reviewer_organization,
    'si8:methodology_version':  assessment.methodology_version,
    'si8:outcome_code':         assessment.outcome,
    'si8:verification_url':     assessment.verification_url,
  }
}
